### PR TITLE
MINDEXER-101 Forward port OSGI improvements to master branch

### PR DESCRIPTION
**Pull request by sesuncedu**
Forward port most OSGI related changes from 5.x to master branch.

Does not include changes to index-reader, as that requires MINDEXER-100 to be applied.

### CODE REVIEW

**Comment by cstamas** [comment]
Manually merged/squashed as
ceb8388e9ca6766877f57901054861bbb713f35f

**Comment by carlspring** [comment]
@sesuncedu,

One thing to mention though -- (nothing critical, just cosmetic) -- you don't seem to be following convention, which is making the checkstyle plugin complain.

**Comment by cstamas** [comment]
@sesuncedu could you please close this PR out?

**Comment by sesuncedu** [comment]
Closed per request

**Comment by jira-importer** [comment]
Resolve #585

**Pull request closed without merging**
