### PR TITLE
Change indexer-reader's Utils to call read() once

### PR DESCRIPTION
**Pull request by sixcorners**
This fixes a resource leak.

### CODE REVIEW

**Comment by sixcorners** [comment]
By resource leak I don't mean an instance of the resource class. I mean an InputStream that doesn't get closed.

**Comment by eolivelli** [comment]
Good catch.
Please create a JIRA and follow the convention for git commits, use 'git log' for examples

**Comment by sixcorners** [comment]
I'll get my pull requests fixed tonight. JIRA was being migrated when you responded.

**Comment by eolivelli** [comment]
Let's wait for CI https://builds.apache.org/job/maven-box/job/maven-indexer/job/MNINDEXER-123/

**Comment by eolivelli** [comment]
CI is okay.
I will merge tomorrow.
Thank you

**Pull request closed without merging**
