### PR TITLE
Add getName() to Record.EntryKey

### PR DESCRIPTION
**Pull request by sixcorners**
I don't want to parse the output from toString()

### CODE REVIEW

**Comment by eolivelli** [comment]
Can you please open a JIRA and change the commit message?
I will be happy to merge, the change is trivial an useful

**Comment by sixcorners** [comment]
Are you saying I should remove "I don't want to parse the output from toString()" or add more detail to the commit message? "I don't want to parse the output from toString()" is only added to the pull request. I didn't put it in the commit message.

I made this: https://issues.apache.org/jira/browse/MINDEXER-122

**Comment by sixcorners** [comment]
I went ahead and added some stuff to the commit message.

**Comment by eolivelli** [comment]
Thanks.
I forgot to link the guide for you
https://maven.apache.org/developers/conventions/git.html

The only missing part is to cite the ticket at the beginning of the message. I can do it

We use JIRA to organize the release notes and keep track of want is delivered on each version.
Maven project is made of about 100 subprojects and we need some paperwork in order not to forget or to follow the wrong way

**Comment by sixcorners** [comment]
Ok. Commit messages have the JIRA ticket name in them and the JIRA tickets have a link to the pull requests. The only thing I didn't do is name my branches to be equal to the name of the JIRA ticket. That would require recreating the pull request. : \ I could do that though if you want.
Thanks for walking me helping me learn the process.

**Comment by eolivelli** [comment]
No need to rename the branch.

**Comment by eolivelli** [comment]
Let's wait for CI
https://builds.apache.org/job/maven-box/job/maven-indexer/job/MINDEXER-122/

**Comment by eolivelli** [comment]
CI is okay I will merge tomorrow

**Comment by slachiewicz** [comment]
Thx merged with 09d3582

**Comment by sixcorners** [comment]
Should I close this?

**Comment by slachiewicz** [comment]
Yes, please

**Pull request closed without merging**
