### PR TITLE
[MINDEXER-117] Add ability to set the temporary index directory for index update

### PR DESCRIPTION
**Pull request by fuss86**

### CODE REVIEW

**Comment by fuss86** [comment]
Hi guys,
would you mind enabling the possibility to set up an index temp directory ?

**Comment by carlspring** [comment]
@cstamas ,

Would you be so kind to review and merge this?
Many thanks in advance! :)

**Comment by carlspring** [comment]
@eolivelli ,

Would you mind adding a Jenkins job to check this as well?

@eolivelli , @sormuras ,

Could you please review and merge this pull as well? Please, let us know, if you have any concerns!

**Comment by fuss86** [comment]
I'll go back to this task soon, thanks for your notes :)

**Comment by fuss86** [comment]
BTW, we are currently using this option in [strongbox](https://github.com/strongbox/strongbox/blob/master/strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/src/main/java/org/carlspring/strongbox/storage/indexing/downloader/IndexDownloader.java#L71) project.

**Comment by fuss86** [comment]
I'll be back to this PR soon :)

**Comment by slachiewicz** [comment]
@fuss86 timeout ;-) 29 days later :)

Rebased in 6c2609fa96671fd9d7741984d5c3ea10be0eb1be and test in 4a54f5f6fee979f8169d710c82247746ed69b9a4

**Comment by fuss86** [comment]
Thanks @slachiewicz :) 79 days later :)

@eolivelli, can we merge it ?

**Comment by eolivelli** [comment]
@fuss86
I left a couple of comments
I don't see them resolved

I will be happy

**Comment by eolivelli** [comment]
Please also create a JIRA and add the is of the JIRA to the beginning of the commit message, see 'git log' for example

**Comment by fuss86** [comment]
> I wonder hiw we can add a minimal test that covers this change.
> Maybe just running the indexer and setting the new field is enough.
> Can you please add such test?

added by @slachiewicz in https://github.com/apache/maven-indexer/commit/4a54f5f6fee979f8169d710c82247746ed69b9a4

> One question: if the directory is not empty we can have unpredictable behavior.
> Should we state this in a javadoc?

It's used to store the index temporarily. It's name is `indexTempDir`. What kind of unpredictable behavior user may expect here ?

> We can't empty the directory automatically

We are not emptying directory :)

**Comment by eolivelli** [comment]
I am sorry.
I only checked this pr and not @slachiewicz work.
I think this patch is good to go.
As @slachiewicz completed the work it is better that he does the merge

+1 from me

Thanks

If @slachiewicz does not merge it because he does not have much time I will be happy to do it

**Comment by fuss86** [comment]
> Please also create a JIRA and add the is of the JIRA to the beginning of the commit message, see 'git log' for example

I've created https://issues.apache.org/jira/browse/MINDEXER-119 and then realized @slachiewicz did it first https://issues.apache.org/jira/browse/MINDEXER-117. Please close https://issues.apache.org/jira/browse/MINDEXER-119 as a duplicate of https://issues.apache.org/jira/browse/MINDEXER-117

**Comment by fuss86** [comment]
@eolivelli please approve this PR if you are +1 :) Thanks !

**Comment by slachiewicz** [comment]
hi, fast '_academic_' question - should we use File or move to Path ?

**Comment by fuss86** [comment]
`File` is used around the indexer code, but I'm keen on helping you migrate indexer to `Path` as a follow-up task :)

**Comment by slachiewicz** [comment]
Thx code merged. Lets review remaining PRs.

**Comment by fuss86** [comment]
Hi @slachiewicz :)

> hi, fast 'academic' question - should we use File or move to Path ?

as said above, I'm keen on helping you guys doing this, but it's quite a big change (that probably deserves next 6.2.X version). Don't you think we could consider releasing current version to 6.1.0 ?

> Thx code merged. Lets review remaining PRs.

Thanks again :) Would you like me to take a look or it was a comment for other ASF guys ?

**Pull request closed without merging**
