### PR TITLE
resolve performance loss due to lucene 4.8.1 - upgrade to lucene 553 and additional fixes

### PR DESCRIPTION
**Pull request by tstupka**
since lucene was upgraded to 4.8.1 the indexer takes 2.5x longer than with lucene 3.6. This seems be a cumulative effect of partial reductions in performance introduced in particular lucene releases after 3.6 - see also https://issues.apache.org/jira/browse/MINDEXER-99

see the particular commits in this request. Each addresses a suggestion for a specific improvement. When all applied, the resulting performance is comparable with the performance before the above mentioned upgrade.
# 0bb9484 - upgrading lucene from 4.8.1 to 5.5.3

performance was improved in lucene 5.x.
with 5.5.3 the indexer works significantly faster than with 4.8.1
# 3cfa430 - avoid rebuilding groups after reading index

after generating the index it has to be re-read one more time to extract a distinct list of allGroups and rootGroups, even though that info was already available, but thrown away.
# 8b98a49 - improve reading from zip file
#4062146 - do not unnecessarily force merge on index writer

merge is very expensive - lets trust lucene to merge when it seems fit. 
the final index size without force merges was 910mb compared to 900mb with fm.
the time improvement is aprox 30%

### CODE REVIEW

**Comment by carlspring** [comment]
@cstamas : Would you mind reviewing this and maybe merging it?

**Comment by michael-o** [comment]
Looking at your changes, they are not really related. They all require appropriate JIRA issues and seperate PRs.

**Comment by cstamas** [comment]
Manually merged/squashed as
532ea64eecd499d047bf4211b6a5bde41f1a7c72

**Comment by cstamas** [comment]
@tstupka could you please close this PR out?

**Comment by jira-importer** [comment]
Resolve #606

**Comment by jira-importer** [comment]
Resolve #606

**Pull request closed without merging**
