### PR TITLE
Add ResourceHandler implementations

### PR DESCRIPTION
**Pull request by sixcorners**
1. What do you all use to format this code?
2. I need to add unit tests to these but before that I want to ask:
3. Do you all think it would be a good idea if the library provided some ready to use implementations of ResourceHandlers?

### CODE REVIEW

**Comment by slachiewicz** [comment]
Thank you for proposal. Could you create Jira task for this improvement?

**Comment by sixcorners** [comment]
Made this: https://issues.apache.org/jira/browse/MINDEXER-124

**Comment by sixcorners** [comment]
Added "throws IOException" back to the empty close methods.
I didn't want to lock in that API to never throw IOExceptions.
If #46 gets merged then omitting "throws IOException" would prevent removing the close methods without a breaking API change.

**Comment by sixcorners** [comment]
Removed the thing where I made the overridden methods return the more specific type using co-variant return types. Returning BufferedReader or BufferedInputStream doesn't really help people using the API a lot but it does lock in the implementation that has to be returned.

**Comment by sixcorners** [comment]
Is there a way to put a work in progress tag on this?
Kind of just wanted to create this to get feedback for now.

**Comment by cstamas** [comment]
Obsoleted by https://github.com/apache/maven-indexer/pull/199

**Pull request closed without merging**
