### PR TITLE
MINDEXER-100

### PR DESCRIPTION
**Pull request by sesuncedu**
Forward port changes from maven-indexer-5.x branch to master.
Minor fixes to pom.xml's and test resources. 
Manually set org.apache.maven.index.reader package version to 1.0.0 instead of default.

### CODE REVIEW

**Comment by cstamas** [comment]
Manually merged/squashed as
6cb2fcbe47883cd0decac0295493bef6577d7eb4

**Comment by cstamas** [comment]
Seems I have no perms to manage GH mirror, so cannot close this PR

**Comment by cstamas** [comment]
@sesuncedu could you please close this PR out?

**Comment by sesuncedu** [comment]
Closed per request

**Comment by jira-importer** [comment]
Resolve #545

**Comment by jira-importer** [comment]
Resolve #545

**Pull request closed without merging**
