### PR TITLE
Bail out from Jenkins

### PR DESCRIPTION
**Pull request by cstamas**
Stop using Jenkins, as we agreed, we will use GH Actions only.

### CODE REVIEW

**Comment by olamy** [comment]
> Stop using Jenkins, as we agreed, we will use GH Actions only.

I didn;t hear anything 
maybe explain the problem?

**Comment by olamy** [comment]
-1
Personally as we are an opensource project, I still prefer promote opensource projects rather than commercial company.
Or at least both for equity!

**Comment by cstamas** [comment]
There was an informal agreement on Apéro to leave ASF Jenkins, as it not only does not buys us anything, but is a chore for us and ASF Infra as well. Also, it has quite some limitations (no macOS) and some issues that seems never gonna be fixed (like overly eager triggering of jobs rebuilding, that consumes all the slaves -- ask @slawekjaranowski  about this issue). Hence, ASF Jenkins is really just a set-back for us, many times it just delays CI results for us.

While I agree about OSS thing, OTOH we should be pragmatic as well. CI is infra, is not something we build against. Or in other words, you suggest to go back to ASF Subversion, and stop using GH completely?

Naturally, this needs to go as vote on ML, that did not yet happen (hence "informal"), so this is just an experiment.

**Comment by michael-o** [comment]
I want BitKeeper.

**Comment by olamy** [comment]
> There was an informal agreement on Apéro to leave ASF Jenkins, as it not only does not buys us anything, but is a chore for us and ASF Infra as well. Also, it has quite some limitations (no macOS) and some issues that seems never gonna be fixed (like overly eager triggering of jobs rebuilding, that consumes all the slaves -- ask @slawekjaranowski about this issue). Hence, ASF Jenkins is really just a set-back for us, many times it just delays CI results for us.
> 
> While I agree about OSS thing, OTOH we should be pragmatic as well. CI is infra, is not something we build against. Or in other words, you suggest to go back to ASF Subversion, and stop using GH completely?
> 

my comment said `Or at least both for equity!` 
not really but maybe we could move as well to a gradle build? instead of the slow Maven not supporting incremental build and nobody fixing it....

> Naturally, this needs to go as vote on ML, that did not yet happen (hence "informal"), so this is just an experiment.

**Comment by olamy** [comment]
> There was an informal agreement on Apéro to leave ASF Jenkins, as it not only does not buys us anything, but is a chore for us and ASF Infra as well. Also, it has quite some limitations (no macOS) and some issues that seems never gonna be fixed (like overly eager triggering of jobs rebuilding, that consumes all the slaves -- ask @slawekjaranowski about this issue). Hence, ASF Jenkins is really just a set-back for us, many times it just delays CI results for us.
> 

not sure what the issues are? I never heard anything.

And by the way if some features are missing we can help other projects to implement those features.
that's the beauty of opensource communities spirit isn't it?
sorry I'm probably a too old guy who believe in some dreams... 🤣

**Comment by cstamas** [comment]
@olamy you still stick to your -1 here?

**Comment by cstamas** [comment]
@slawekjaranowski thanks for chiming in with meaningful information, hence, am closing this for now

**Pull request closed without merging**
