### PR TITLE
Fix issue tracker URI in README

### PR DESCRIPTION
**Pull request by sewe**
Codehaus is not longer available.

### CODE REVIEW

**Comment by ebarboni** [comment]
hi, if you edit the PR title to contains MINDEXER-105 it will connect the githb to to the related jira issue.

**Comment by sewe** [comment]
> hi, if you edit the PR title to contains MINDEXER-105 it will connect the githb to to the related jira issue.

@ebarboni Done.

**Comment by jira-importer** [comment]
Resolve #524

**Comment by jira-importer** [comment]
Resolve #524

**Pull request closed without merging**
