### PR TITLE
MINDEXER-171 Support SHA256 and SHA512 HashType

### PR DESCRIPTION
**Pull request by GrzegorzSmardzewskiAllegro**
Adds support for .sha256 and .sha512 checksum files

### CODE REVIEW

**Comment by cstamas** [comment]
This is tricky, especially since https://issues.apache.org/jira/browse/MRESOLVER-230

**Comment by GrzegorzSmardzewskiAllegro** [comment]
This only adds support for parsing GAVs for the indexer. Currently the indexer crashes when it's run on a repository that has .sha256 or .sha512 files.

**Comment by cstamas** [comment]
Crashes? Can I have the stack trace pls? Or better, make it a MNDEXER JIRA?

**Comment by GrzegorzSmardzewskiAllegro** [comment]
I edited the [original issue](https://issues.apache.org/jira/browse/MINDEXER-171) with additional details.

**Review by cstamas — APPROVED** [review]

**Comment by jira-importer** [comment]
Resolve #573

**Pull request merged**
