### PR TITLE
[MINDEXER-115] Migrate to BooleanQuery.Builder

### PR DESCRIPTION
**Pull request by slachiewicz**
Remove deprecated usages of BooleanQuery constructor - use Builder

Based on Sopot Cela changes

### CODE REVIEW

**Comment by slachiewicz** [comment]
@carlspring @fuss86 could You check if this patch is ok and would not introduce any regression?

**Comment by fuss86** [comment]
Hi @slachiewicz !

Have you tried building your branch ?

It seems you've got at least 2 checkstyle violations.

```
[INFO] --- maven-checkstyle-plugin:2.17:check (checkstyle-check) @ indexer-examples-basic ---
[INFO] There are 3 errors reported by Checkstyle 6.11.2 with config/maven_checks.xml ruleset.
[ERROR] src\main\java\org\apache\maven\indexer\examples\BasicUsageExample.java:[244] (sizes) LineLength: Line is longer than 120 characters (found 128).
[ERROR] src\main\java\org\apache\maven\indexer\examples\BasicUsageExample.java:[317] (sizes) LineLength: Line is longer than 120 characters (found 131).
[INFO] Ignored 1 error, 2 violations remaining.
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Maven-Indexer ...................................... SUCCESS [ 23.165 s]
[INFO] Maven :: Indexer Core .............................. SUCCESS [ 49.780 s]
[INFO] Maven :: Indexer CLI ............................... SUCCESS [  7.111 s]
[INFO] Maven :: Indexer Reader ............................ SUCCESS [  6.901 s]
[INFO] Maven :: Indexer Examples .......................... SUCCESS [  0.746 s]
[INFO] Maven :: Indexer Examples [Basic] .................. FAILURE [  3.363 s]
[INFO] Maven :: Indexer Examples [Spring] ................. SKIPPED
```

**Comment by fuss86** [comment]
@slachiewicz, I cherry-picked your commit into our fork and all unit and integrations tests have passed. No regression on our side spotted.

Hope it helps :)

**Comment by slachiewicz** [comment]
Thx @fuss86 for testing. I fixed checkstyle issuess and code now is on master.

**Comment by jira-importer** [comment]
Resolve #565

**Comment by jira-importer** [comment]
Resolve #565

**Pull request merged**
