### PR TITLE
[MINDEXER-177][MINDEXER-178] Update Lucene and modernizer

### PR DESCRIPTION
**Pull request by cstamas**
Updates to dependencies:
* Lucene 9.4.2

Updates to plugins:
* modernizer 2.5.0

---

https://issues.apache.org/jira/browse/MINDEXER-177 
https://issues.apache.org/jira/browse/MINDEXER-178

### CODE REVIEW

**Comment by slachiewicz** [comment]
Closes #270

**Comment by jira-importer** [comment]
Resolve #609

**Comment by jira-importer** [comment]
Resolve #626

**Comment by jira-importer** [comment]
Resolve #609

**Comment by jira-importer** [comment]
Resolve #626

**Pull request merged**
