### PR TITLE
MINDEXER-102 - indexer-reader OSGI changes forward ported to master

### PR DESCRIPTION
**Pull request by sesuncedu**
Forward ports index-reader changes from MINDEXER-97. 

Requires/includes  MINDEXER-100, which forward ports other changes from 5.x to master. 

New commit is https://github.com/sesuncedu/maven-indexer/commit/171f0902f9424c8fed8bc6ca4f62eec6fa1759c6

Does not include MINDEXER-101, which forwards ports other OSGI related changes from MINDEXER-97.

### CODE REVIEW

**Comment by sesuncedu** [comment]
I have changed the package version for index-reader to 5.2.0, since there is a  minor level change from 5.1.2.snapshot.

**Comment by cstamas** [comment]
Manually merged/squash as
0ee33793657d37b5475e8b57c97af9ce1358f553

**Comment by cstamas** [comment]
@sesuncedu could you please close this PR out?

**Comment by sesuncedu** [comment]
I'll close them all out except for the one tagged MINDEXER-97, so that I can file an issue asking why it didn't get auto-closed :-)

**Comment by sesuncedu** [comment]
Also, the packageinfo change to 5.2.0 didn't take. I will submit as a separate PR, though I'm likely to make some changes in the near term that might require a major bump which would moot that :)

**Comment by jira-importer** [comment]
Resolve #624

**Pull request closed without merging**
