### PR TITLE
When is the next release due?

### PR DESCRIPTION
**Pull request by gatesn**
(GitHub issues aren't enabled so figured I'd ask via PR)

There are a few fixes I'd like to pick up, notably the input stream leak in https://github.com/apache/maven-indexer/commit/13beea98584008efc375e738f2acee08ce367727

### CODE REVIEW

**Comment by carlspring** [comment]
There is no scheduled date.

I would personally like to see Lucene upgraded the more recent versions of Lucene. Would you be interested in looking into this as well? :)

**Comment by gatesn** [comment]
Is there any reason to block the release on that? In the extreme, what's the downside to releasing after every commit?

**Comment by Tibor17** [comment]
There's been quite a lot of commits after the latest release.
Ask the developers on the dev-mailing list. The developers may want to add something as well, so the due date must be an agreement in the community.

**Comment by eolivelli** [comment]
Yes, the best please is on dev@maven.apache.org mailing list

**Pull request closed without merging**
