### PR TITLE
MINDEXER-97:  Index/Store Extra OSGI Headers

### PR DESCRIPTION
**Pull request by sesuncedu**
* Add "Provide-Capability", "Require-Capability", and "Fragment-Host" to the set of indexed+stored manifest headers.
* Calculate, index, and store SHA-256 checksum for bundle artifacts (required by the osgi repository service).
* Add tests for new fields to OsgiArtifactIndexCreatorTest
* Add new fields to index-reader library.
* Bump serialization version UID

This PR does not index/store the  DynamicImport-Package header, as this header is not used during resolution. 

Note that calculation of the SHA-256 checksum requires performing a sequential read of the entire artifact.

### CODE REVIEW

**Comment by balazs-zsoldos** [comment]
+1

**Comment by carlspring** [comment]
Hi,

Shouldn't this be applied to the `master` branch and be included in `6.0` instead?

@cstamas : What do you think?

Cheers,

Martin

**Comment by sesuncedu** [comment]
I have been consistently confused about which branch is live, so it would not surprise me either way ☺️. 
I had been working against main on some code to use the central index to build a database for use as an OSGI resolver. I noted the missing fields... after I'd done a whole bunch of defactoring to decouple index reading from the rest of the code.... D'oh! 

I can cross port these changes to master (well, not the index reader ones) :) My main goal is to get the extra fields into the index on central. I'd presume that 5.1.2 would be the smaller jump. 

Would it be possible to make a 5.1.2 release? And would it be possible to have  run it running on central in the near future?

 My primary concern if I were the admin would be the need to perform the sequential read of the entire bundle jar to generate the sha-256 checksum. It ought not be too significant a burden compared to the overall level of activity, but depending on what else is going on on the storage side, it might be annoying. 

I haven't checked  to see how full  reindexing is handled, and if a previously calculated SHA-256 could be fetched for less than the cost of the sequential read (lucene + cache + storage load / architecture = magic). Alternative would be to save SHA-256 hashes in a simple k/v store. 

 (now that full sha-1 has been broken, it is probably time to switch over to SHA-256, but that's a much more pervasive change).

**Comment by sesuncedu** [comment]
Also, OSGI headers really need a custom analyzer, as they have their own nested organization and datatyping. It doesn't seem worth it for this change, but would be worth it for the next major if that were going to lucene 6 (version number comparison + range searches could possibly be handled with a bit of trie-abuse. Qualifiers are the real headache, especially since maven and OSGI have different opinions about whether 5.0.0[.-]SNAPSHOT is in the range [4.3.0,5).   )

**Comment by sesuncedu** [comment]
Also, if I do forward port, should I also try and forward port index-reader? 

And, if you are thinking of releasing 5.1.2, would you like me to do a more detailed  job of bundle making (e.g. extracting a pure api into a separate package, making the implementation private, adding per-package version numbers, and adding an activator to bind the implementation as a service). 

I'd also attach the bundle baseline task to the verify stage, even though it can't really do much till there's been a previous release to compare against.

**Comment by sesuncedu** [comment]
I have changed the package version for the indexer to 5.2.0 because there are minor changes from prior 5.1.2.SNAPSHOT versions. The overall 5.x release version might want to skip to 5.1.3 since 5.1.2-SNAPSHOT has been around for so long.  I am tempted to set the bundle version for index-reader to 5.2.0, to avoid possible confusion.

**Comment by cstamas** [comment]
I'd leave maven-indexer-5.x branch as is, everything is on master now. 

Sorry for the squashes, but I did not want to fiddle with "arrival times". 
All the commit origins are on commit messages and reference back to PRs here.

**Comment by sesuncedu** [comment]
@cstamas Squashbasing gives the cleanest trees. Just make sure to give yourself credit for the commits of yours that were cherry-picked. 

index-reader should be identical for both branches. There's only a single package, and  I bumped the OSGI package version to 5.2.0, since the additional public static fields are a minor API change over 5.1.2 .  Since nexus is using karaf features / pax-aether-url , this isn't as necessary or helpful or as it might be, but it does mean that the feature assembly can safely refer to the 6.0 index-reader snapshot, since the osgi package version is explicitly backwards compatible. 

I actually ended up doing a third version of the changes as kludges on top of the nexus-public maven repository plugin. The main annoyance with index-reader was having to subclass  Expander / Compactor to handle the additional fields,  where a default mapping would have been simple.  

  Since I needed to build some mapping tables anyway to stash the relevant manifest headers in an asset child map where they wouldn't get in the way, doing Expander/Compactor wasn't that much of an extra hassle, but if the index-reader is used to build federations, it is useful to be able to have unrecognized fields be passed through as strings (e.g. if jigsaw is released, exchanging headers from module-info.class (and now possibly the manifest?) will be useful for federated systems).

**Comment by cstamas** [comment]
@sesuncedu could you please close this PR out?

**Comment by sesuncedu** [comment]
As mentioned for MINDEXER-102, I'm leaving this PR temporarily open, so I can file JIRA issue on why it wasn't auto-closed.

**Comment by cstamas** [comment]
Am closing this PR as it was already merged and released in 6.0.0

**Comment by jira-importer** [comment]
Resolve #527

**Comment by jira-importer** [comment]
Resolve #527

**Comment by jira-importer** [comment]
Resolve #527

**Pull request closed without merging**
