### PR TITLE
[MINDEXER-114] Extend JarFileContentsIndexCreator to support zip files

### PR DESCRIPTION
**Pull request by fuss86**

### CODE REVIEW

**Comment by fuss86** [comment]
Hi guys, would you mind enabling support for `.zip` artifact packages, to be able to index Java class names from a ZIP Maven artifacts too ?

**Comment by carlspring** [comment]
@cstamas ,

Would you be so kind to review and merge this?
Many thanks in advance! :)

**Comment by fuss86** [comment]
Hi @eolivelli ,

I've added a test case and rebased to latest master. 

Regards :)

**Comment by eolivelli** [comment]
Looks good to me

Can you please create a jira here https://issues.apache.org/jira/projects/MINDEXER/summary/statistics
Then squash all in a single commit with the jira id in the beginning of the commit message?

**Comment by fuss86** [comment]
Done :)

**Comment by eolivelli** [comment]
This is the CI job
https://builds.apache.org/job/maven-box/job/maven-indexer/job/MINDEXER-114/

**Comment by carlspring** [comment]
Great, the build is passing! :)

@eolivelli , are you happy to approve this?

Also, @cstamas , @slachiewicz , @sormuras , @khmarbaise , could you please cut a release for us with this and the changes from #26 ? We've been depending on our forked version of the `maven-indexer` for quite a while now and we'd like to start stabilizing our dependencies.

Many thanks in advance! :)

**Comment by eolivelli** [comment]
There is a test failure.
I am investigating. It can be a flake due to Windows way of dealing with file deletion
Sorry, this is taking so much time.

**Comment by eolivelli** [comment]
It seems that a test is failing consistently on this branch and not on master branch.

Can you double check, just follow the link to the CI job.
We have a job for each branch, the test is failing on MINDEXER-114  and not on master

**Comment by carlspring** [comment]
@eolivelli ,

We have a Jenkins build for this [here](https://jenkins.carlspring.org/job/opensource/job/maven-indexer/job/master/5/). This is based on our fork's `master`, which is simply a copy of yours with the two merged in pull requests (#25 , #26). Please, check [here](https://github.com/carlspring/maven-indexer/commits/master).

**Comment by steve-todorov** [comment]
@eolivelli ,

I've just tested this PR on a windows machine using the same build command from your window's jenkins job. Unfortunately I am not able to reproduce the error you get in your Jenkins:

```
$ cd C:\maven-indexer

$ git log -1
commit 121b51a9fb5ae2026484ea075293f442ef10aa8a (HEAD -> pr/25)
Author: Przemyslaw Fusik
Date:   Thu Jan 25 00:31:14 2018 +0100

    [MINDEXER-114] Extend JarFileContentsIndexCreator to support zip files

$ mvn -V -P+run-its -Dmaven.test.failure.ignore=true -Dfindbugs.failOnError=false -Dfindbugs.skip=true clean verify

Apache Maven 3.5.2 (138edd61fd100ec658bfa2d307c43b76940a5d7d; 2017-10-18T10:58:13+03:00)
Maven home: C:\java\apache-maven-3.5.2-bin
Java version: 1.8.0_162, vendor: Oracle Corporation
Java home: C:\java\jdk1.8.0_162\jre
Default locale: en_US, platform encoding: Cp1252
OS name: "windows server 2016", version: "10.0", arch: "amd64", family: "windows"

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Maven-Indexer ...................................... SUCCESS [  6.281 s]
[INFO] Maven :: Indexer Core .............................. SUCCESS [02:29 min]
[INFO] Maven :: Indexer CLI ............................... SUCCESS [ 53.974 s]
[INFO] Maven :: Indexer Reader ............................ SUCCESS [  9.572 s]
[INFO] Maven :: Indexer Examples .......................... SUCCESS [  1.344 s]
[INFO] Maven :: Indexer Examples [Basic] .................. SUCCESS [  3.418 s]
[INFO] Maven :: Indexer Examples [Spring] ................. SUCCESS [  4.157 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 03:49 min
[INFO] Finished at: 2019-04-05T20:52:03+03:00
[INFO] Final Memory: 86M/795M
[INFO] ------------------------------------------------------------------------
```

I have built this PR multiple times and all attempts were successful. It looks to me like the build failure might be a false-positive related to an issue with the agent (not sure what exactly, maybe the workspace needs to be cleared and if there is enough space?).

**Comment by slachiewicz** [comment]
@eolivelli maybe streams where not closed with plexus-utils,  please try to apply quick fix #35

**Comment by eolivelli** [comment]
I have merged #35

**Comment by slachiewicz** [comment]
great! could you also rebase MINDEXER-114 branch on master to check if it helped with CI build?

**Comment by fuss86** [comment]
rebased :)

**Comment by slachiewicz** [comment]
Build passed ok
LGTM

**Comment by carlspring** [comment]
@slachiewicz : 
It looks like this PR was closed without merging. Was this by accident, or am I missing something...?

**Comment by fuss86** [comment]
It's in the `master` branch https://github.com/apache/maven-indexer/commits/master, @carlspring

**Comment by carlspring** [comment]
Thanks for clarifying! :)

**Comment by slachiewicz** [comment]
yes, merged in https://github.com/apache/maven-indexer/commit/915530e242b9e5b509b8d2ead796b6a79258ec23
Thanks for patch.

**Pull request closed without merging**
